import type { StackableEffectType } from "@/store/types";

/** Display name per stackable effect type — grows one entry per type each phase.
 *
 * A handful of these intentionally diverge from the obvious/generic name for what the
 * effect does (e.g. "Faceted" rather than "Cubify", "Fluted Glass" rather than "Reeded
 * Glass") — confirmed against a competing effects tool's own public effect list,
 * distinctive/coined names it uses were renamed here so this app doesn't just read as
 * a copy. Plain industry-standard terms that happen to coincide (Curves, Levels,
 * Vignette, Threshold, Duotone, Gaussian Blur, Bloom, CRT, LED, Frame Drop, Grunge,
 * Vintage Film, Motion Trails, Modulation, Ink Bleed, Blob Tracker, Star Glow — kept
 * as plain "Glow", ...) were deliberately left alone (or shortened, for CRT/LED) —
 * renaming a term the whole industry already uses (or one the user specifically
 * prefers unchanged) wouldn't differentiate anything, it'd just make the effect
 * harder to recognize. */
export const EFFECT_LABELS: Record<StackableEffectType, string> = {
  halftone: "Halftone",
  rgbShift: "RGB Shift",
  edgeBlend: "Edge Blend",
  gaussianBlur: "Gaussian Blur",
  motionBlur: "Motion Blur",
  cameraShake: "Camera Shake",
  bloom: "Bloom",
  starGlow: "Glow",
  dither: "Dither",
  xerox: "Xerox",
  pixelate: "Pocket LCD",
  ascii: "ASCII Art",
  glitch: "Glitch",
  vhs: "VHS",
  ntsc: "NTSC",
  modulation: "Modulation",
  ledScreen: "LED",
  motionTrails: "Motion Trails",
  grunge: "Grunge",
  vintagePrint: "Vintage Print",
  mixedMedia: "Mixed Media",
  thinPaper: "Thin Paper",
  wetPaper: "Wet Paper",
  teleshopping: "Teleshopping",
  blobTracker: "Blob Tracker",
  curves: "Curves",
  levels: "Levels",
  exposure: "Exposure",
  contrast: "Brightness/Contrast",
  whiteBalance: "White Balance",
  hueSaturation: "Hue/Saturation",
  colorBalance: "Color Balance",
  gradientMap: "Gradient Map",
  duotone: "Duotone",
  monochrome: "Monochrome",
  thermal: "Thermal",
  colorMatrix: "Color Matrix",
  rgbGain: "RGB Gain",
  hueCurves: "Hue Curves",
  colorGrading: "Color Grading",
  circularBlur: "Circular Blur",
  radialBlur: "Radial Blur",
  zoomBlur: "Zoom Blur",
  blurSharp: "Blur/Sharp",
  depthOfField: "Depth of Field",
  swirl: "Swirl",
  pinch: "Pinch",
  perspective: "Perspective",
  ripple: "Ripple",
  emboss: "Emboss",
  polarCoords: "Polar Warp",
  elasticGrid: "Warp Grid",
  vignette: "Vignette",
  threshold: "Threshold",
  reededGlass: "Fluted Glass",
  cubify: "Faceted",
  transform: "Transform",
  risograph: "Risograph",
  stripe: "Stripe",
  noise: "Noise",
  frameDrop: "Frame Drop",
  crtScreen: "CRT",
  inkBleed: "Ink Bleed",
  paperScan: "Flatbed Scan",
  blackAndWhite: "Black & White",
  classicFilm: "Classic Film",
  vintageFilm: "Vintage Film",
  displacement: "Displacement",
  filmGrain: "Film Grain",
  halation: "Halation",
};

/** One-line description shown under a gallery card's name — the "more descriptive,
 * not just symbols" requirement, so what an effect does is legible without having to
 * infer it from the thumbnail alone. */
export const EFFECT_DESCRIPTIONS: Record<StackableEffectType, string> = {
  halftone: "Classic dot, line, or CMYK hatch print screen",
  rgbShift: "Linear or lens-style radial chromatic aberration, independent per channel",
  edgeBlend: "Soft ambient glow behind the image",
  gaussianBlur: "Uniform soft blur",
  motionBlur: "Directional streaked blur",
  cameraShake: "Blurred handheld-jitter look",
  bloom: "Bright highlights bloom outward",
  starGlow: "Bright highlights radiate into a multi-ray star",
  dither: "Retro reduced-palette dot pattern",
  xerox: "High-contrast photocopier look",
  pixelate: "Chunky pixels, green LCD look",
  ascii: "Luminance rendered as text characters",
  glitch: "Datamoshed horizontal band displacement, seeded and density-tunable",
  vhs: "Scanlines, color bleed, and tape grain",
  ntsc: "Analog broadcast smear and interlace flicker",
  modulation: "Luminance-driven scan lines on black, like an oscilloscope trace of the photo",
  ledScreen: "Close-up LED-matrix sub-pixel grid",
  motionTrails: "Threshold-bright pixels trailed into wavy streaks",
  grunge: "Heavy grain, cool tint, boosted contrast",
  vintagePrint: "Warm sepia tint, faded aged-photo contrast",
  mixedMedia: "Neutral paper texture with a light desaturating wash",
  thinPaper: "High-key, washed-out newsprint look",
  wetPaper: "Dark, blotchy, cool-toned ink-bleed look",
  teleshopping: "Soft warm glow, lifted brightness, infomercial look",
  blobTracker: "Sci-fi reticles on real detected high-contrast regions",
  curves: "Draggable tone curve, applied to all channels",
  levels: "Photoshop-style black/white/gamma point remap",
  exposure: "Photographic stops, computed in true linear light",
  contrast: "Brightness plus a smooth S-curve contrast boost",
  whiteBalance: "Kelvin temperature and green/magenta tint via real chromatic adaptation",
  hueSaturation: "Hue rotation, saturation, and lightness via true HSL",
  colorBalance: "Shadows/midtones/highlights cyan-red, magenta-green, yellow-blue push",
  gradientMap: "Recolors by luminance through a custom gradient",
  duotone: "Classic 2-ink shadow/highlight color mapping",
  monochrome: "Weighted-channel grayscale with darkroom color-filter control, plus tint",
  thermal: "False-color Ironbow thermal-camera palette",
  colorMatrix: "Raw 3x3 channel-mixing matrix with per-channel offset",
  rgbGain: "Per-channel gain in true linear light",
  hueCurves: "Hue, saturation, and lightness curves indexed by hue",
  colorGrading: "3-way shadows/midtones/highlights color wheels plus luminance",
  circularBlur: "Uniform disc/bokeh-style blur, not a soft gaussian falloff",
  radialBlur: "Rotational spin blur around a center point",
  zoomBlur: "Radial zoom-burst streaks toward/away from a center",
  blurSharp: "One slider: blur one way, real unsharp-mask sharpen the other",
  depthOfField: "Iris or tilt-shift focus falloff over a true variable-radius blur",
  swirl: "Rotational pinwheel twist around a center",
  pinch: "Radial pinch or bulge distortion around a center",
  perspective: "Real projective corner-pin transform",
  ripple: "Concentric wave displacement from a center",
  emboss: "Directional-derivative raised relief look",
  polarCoords: "Wraps a photo into a circle, or unwraps one",
  elasticGrid: "Draggable 5x5 mesh warp",
  vignette: "Photographic edge darkening or lightening",
  threshold: "Hard (or softened) black/white luminance cutoff",
  reededGlass: "Fluted-glass vertical rib refraction",
  cubify: "Jittered polygonal cell faceting (Crystallize)",
  transform: "Draggable translate/scale/rotate/skew of the layer's content",
  risograph: "2-ink spot-color print separation with misregistration",
  stripe: "Irregular inkjet/thermal print-head banding",
  noise: "Flat per-pixel sensor/signal noise, colored or mono",
  frameDrop: "Blocky MPEG-style macroblock corruption",
  crtScreen: "Barrel curvature, phosphor mask, and scanlines",
  inkBleed: "Ink feathering into paper fibers at high-contrast edges",
  paperScan: "Warm scanner-light cast with uneven lighting and grain",
  blackAndWhite: "Curated panchromatic film-stock black & white look",
  classicFilm: "A well-preserved, gentle color-negative film emulation",
  vintageFilm: "Faded, scratched, heavily-grained aged film stock",
  displacement: "Smooth organic film-gate-weave misalignment",
  filmGrain: "Luminance-dependent organic emulsion grain",
  halation: "Warm red glow bleeding around bright highlights",
};

/** Which gallery category each effect belongs to — grows alongside the effect list
 * itself; the Effects gallery groups its cards by this, one section per category
 * that currently has at least one effect (see EffectsDrawer.tsx). */
export const EFFECT_CATEGORIES: Record<StackableEffectType, string> = {
  gaussianBlur: "Blur & Glow",
  motionBlur: "Blur & Glow",
  cameraShake: "Blur & Glow",
  bloom: "Blur & Glow",
  starGlow: "Blur & Glow",
  edgeBlend: "Blur & Glow",
  circularBlur: "Blur & Glow",
  radialBlur: "Blur & Glow",
  zoomBlur: "Blur & Glow",
  blurSharp: "Blur & Glow",
  depthOfField: "Blur & Glow",
  swirl: "Distort",
  pinch: "Distort",
  perspective: "Distort",
  ripple: "Distort",
  emboss: "Distort",
  polarCoords: "Distort",
  elasticGrid: "Distort",
  rgbShift: "Glitch & Signal",
  glitch: "Glitch & Signal",
  vhs: "Glitch & Signal",
  ntsc: "Glitch & Signal",
  modulation: "Glitch & Signal",
  ledScreen: "Glitch & Signal",
  motionTrails: "Effects",
  vignette: "Effects",
  threshold: "Effects",
  reededGlass: "Effects",
  cubify: "Effects",
  transform: "Effects",
  risograph: "Effects",
  halftone: "Print & Halftone",
  dither: "Print & Halftone",
  xerox: "Print & Halftone",
  pixelate: "Print & Halftone",
  ascii: "Print & Halftone",
  grunge: "Texture & Paper",
  vintagePrint: "Texture & Paper",
  mixedMedia: "Texture & Paper",
  thinPaper: "Texture & Paper",
  wetPaper: "Texture & Paper",
  teleshopping: "Texture & Paper",
  blobTracker: "Texture & Paper",
  inkBleed: "Texture & Paper",
  paperScan: "Texture & Paper",
  stripe: "Glitch & Signal",
  noise: "Glitch & Signal",
  frameDrop: "Glitch & Signal",
  crtScreen: "Glitch & Signal",
  blackAndWhite: "Film",
  classicFilm: "Film",
  vintageFilm: "Film",
  displacement: "Film",
  filmGrain: "Film",
  halation: "Film",
  curves: "Color Grading",
  levels: "Color Grading",
  exposure: "Color Grading",
  contrast: "Color Grading",
  whiteBalance: "Color Grading",
  hueSaturation: "Color Grading",
  colorBalance: "Color Grading",
  gradientMap: "Color Grading",
  duotone: "Color Grading",
  monochrome: "Color Grading",
  thermal: "Color Grading",
  colorMatrix: "Color Grading",
  rgbGain: "Color Grading",
  hueCurves: "Color Grading",
  colorGrading: "Color Grading",
};

/** Fixed display order for category sections — categories not yet represented by any
 * effect type simply produce an empty group, filtered out before rendering. */
export const CATEGORY_ORDER = ["Blur & Glow", "Distort", "Glitch & Signal", "Print & Halftone", "Texture & Paper", "Film", "Color Grading", "Effects"];

/** Every currently-implemented stackable effect type, in gallery display order —
 * the single source of truth both the main Effects gallery (EffectsDrawer.tsx) and
 * a Layer Mix branch's own "add effect" picker (MixLayerRow.tsx) draw from, so a
 * newly added effect only needs to be listed here once. */
export const ALL_EFFECT_TYPES: StackableEffectType[] = [
  "gaussianBlur",
  "motionBlur",
  "cameraShake",
  "bloom",
  "starGlow",
  "edgeBlend",
  "circularBlur",
  "radialBlur",
  "zoomBlur",
  "blurSharp",
  "depthOfField",
  "swirl",
  "pinch",
  "perspective",
  "ripple",
  "emboss",
  "polarCoords",
  "elasticGrid",
  "vignette",
  "threshold",
  "reededGlass",
  "cubify",
  "transform",
  "risograph",
  "rgbShift",
  "glitch",
  "vhs",
  "ntsc",
  "modulation",
  "ledScreen",
  "motionTrails",
  "stripe",
  "noise",
  "frameDrop",
  "crtScreen",
  "halftone",
  "dither",
  "xerox",
  "pixelate",
  "ascii",
  "grunge",
  "vintagePrint",
  "mixedMedia",
  "thinPaper",
  "wetPaper",
  "teleshopping",
  "inkBleed",
  "paperScan",
  "blobTracker",
  "blackAndWhite",
  "classicFilm",
  "vintageFilm",
  "displacement",
  "filmGrain",
  "halation",
  "curves",
  "levels",
  "exposure",
  "contrast",
  "whiteBalance",
  "hueSaturation",
  "colorBalance",
  "gradientMap",
  "duotone",
  "monochrome",
  "thermal",
  "colorMatrix",
  "rgbGain",
  "hueCurves",
  "colorGrading",
];

/** The subset of ALL_EFFECT_TYPES usable inside a Layer Mix branch — excludes the
 * three structurally-special types that never go through the shared GPU content
 * pipeline (see getEnabledContentLayers's doc comment in store/imageEffects.ts):
 * adding one inside a branch would silently do nothing, since branch rendering only
 * ever runs the content pipeline. */
export const BRANCH_EFFECT_TYPES: StackableEffectType[] = ALL_EFFECT_TYPES.filter(
  (t) => t !== "edgeBlend" && t !== "ascii" && t !== "blobTracker",
);
